name: petscape
description: take care your pet with petscape.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_screenutil: ^5.5.4
  freezed_annotation: ^2.1.0
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hexcolor: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.5.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_logo_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
