name: petscape
description: take care your pet with petscape.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.2
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  file_picker: ^5.2.2
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  firebase_storage: ^11.0.2
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.5.0
  flutter_chat_ui: ^1.6.5
  flutter_riverpod: ^2.0.2
  flutter_screenutil: ^5.5.4
  flutter_sound: ^9.2.13
  freezed_annotation: ^2.2.0
  go_router: ^5.1.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hexcolor: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  open_filex: ^4.1.1
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_logo_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/petscape/
    - assets/icons/
